### ISSUE TITLE
When a polygon has a circular hole, shape.coords is missing the coordinates of the hole

### ISSUE THREAD

**Issue by maudslice** [mraad/FileGDB#8]
Hi, bro, As the title says, when a polygon has a circular hole, shape.coords is missing the coordinates of the hole.
This is what it looks like when I load a sample feature in arcmap,
<img width="203" alt="截图_20230509130613" src="https://user-images.githubusercontent.com/52091023/236999058-7e55ccf7-4b40-4c20-b21b-65402d634df0.png">
When I convert shape.coords to geometry objects for display in arcmap, it looks like this
<img width="231" alt="截图_20230509130953" src="https://user-images.githubusercontent.com/52091023/236999540-eb34b54e-3ff4-4c77-a626-f7550a8e532b.png">
Obviously, the geometry converted with shape.coords is missing a hole, Zoom in on the map scale to see the missing holes, like this:
<img width="466" alt="截图_20230509131510" src="https://user-images.githubusercontent.com/52091023/237000311-790441b3-bf6e-4bcf-8c96-278ef1e8dd66.png">
I compared the number of coordinates of the two polygon objects, and found that the polygon converted by shape.coords lacks the coordinates of the part that represents the hole.
Next, I compared the coordinates of the two polygons and found that the hole in the polygon constructed from shape.coords seems to have only two identical coordinates.
Finally, I counted some of the polygons where this happens and found that they all lack a circular-like LinearRing.
I'm not sure if there's something I'm missing when read filegdb, and I'd appreciate your help.
Here is the test file that will occur as described above, please use it:
[test.gdb.zip](https://github.com/mraad/FileGDB/files/11426946/test.gdb.zip)

**Comment by mraad** [comment]
Thank u for the data....Are you sure you are reading the geometry correctly? please see attached my display.
<img width="1122" alt="PolyWithHole" src="https://github.com/mraad/FileGDB/assets/984730/9bb1210d-d24d-4eba-be53-c51507211934">

**Comment by maudslice** [comment]
emmm, test.gdb is what I exported from a gdb file with millions of data. The problem I described above does happen when reading that gdb, I'm not sure what happens when exporting, but the problem of missing a hole in the coordinates in test.gdb seems to be fixed, which is really frustrating, but thanks for the reply.
